const items = 
[
  {
    "name": "PlayStation 5 Standard",
    "price": 499.99,
    "description": "La dernière console de Sony avec des graphismes de nouvelle génération et un lecteur de disques.",
    "quantity": 100,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-001",
    "memory": "825GB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Digital Edition",
    "price": 399.99,
    "description": "La version numérique de la PS5 sans lecteur de disques.",
    "quantity": 50,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-002",
    "memory": "825GB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Slim",
    "price": 499.99,
    "description": "La version plus mince et plus légère de la PS5.",
    "quantity": 75,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-003",
    "memory": "825GB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Pro",
    "price": 599.99,
    "description": "La version améliorée de la PS5 avec des performances et des graphismes supérieurs.",
    "quantity": 80,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-004",
    "memory": "1TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Standard 1TB",
    "price": 549.99,
    "description": "La dernière console de Sony avec des graphismes de nouvelle génération et un lecteur de disques.",
    "quantity": 60,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-005",
    "memory": "1TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Digital Edition 1TB",
    "price": 449.99,
    "description": "La version numérique de la PS5 sans lecteur de disques.",
    "quantity": 40,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-006",
    "memory": "1TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Standard 2TB",
    "price": 599.99,
    "description": "La dernière console de Sony avec des graphismes de nouvelle génération et un lecteur de disques.",
    "quantity": 70,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-007",
    "memory": "2TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Digital Edition 2TB",
    "price": 499.99,
    "description": "La version numérique de la PS5 sans lecteur de disques.",
    "quantity": 30,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-008",
    "memory": "2TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Pro 2TB",
    "price": 699.99,
    "description": "La version améliorée de la PS5 avec des performances et des graphismes supérieurs.",
    "quantity": 90,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-009",
    "memory": "2TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Pro 3TB",
    "price": 749.99,
    "description": "La version améliorée de la PS5 avec des performances et des graphismes supérieurs.",
    "quantity": 85,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-010",
    "memory": "3TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Slim 1TB",
    "price": 549.99,
    "description": "La version plus mince et plus légère de la PS5.",
    "quantity": 65,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-011",
    "memory": "1TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Slim 2TB",
    "price": 599.99,
    "description": "La version plus mince et plus légère de la PS5.",
    "quantity": 50,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-012",
    "memory": "2TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Slim 3TB",
    "price": 649.99,
    "description": "La version plus mince et plus légère de la PS5.",
    "quantity": 45,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-013",
    "memory": "3TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Pro Digital",
    "price": 549.99,
    "description": "La version Pro de la PS5 sans lecteur de disques.",
    "quantity": 95,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-014",
    "memory": "1TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
  {
    "name": "PlayStation 5 Pro Digital 2TB",
    "price": 599.99,
    "description": "La version Pro de la PS5 sans lecteur de disques.",
    "quantity": 70,
    "category": "console",
    "subcategory": "PS5",
    "matricule": "PS5-015",
    "memory": "2TB",
    "front_pic": null,
    "back_pic": null,
    "left_pic": null,
    "right_pic": null,
    "up_pic": null,
    "down_pic": null
  },
    {
      "name": "Xbox One",
      "price": 299.99,
      "description": "La console de jeux de Microsoft avec une large bibliothèque de jeux.",
      "quantity": 100,
      "category": "console",
      "subcategory": "Xbox One",
      "matricule": "XBO-001",
      "memory": "500GB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Xbox One S",
      "price": 349.99,
      "description": "La version améliorée de la Xbox One avec des graphismes en 4K.",
      "quantity": 80,
      "category": "console",
      "subcategory": "Xbox One",
      "matricule": "XBO-002",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Xbox One X",
      "price": 499.99,
      "description": "La console la plus puissante de Microsoft avec des performances en 4K.",
      "quantity": 90,
      "category": "console",
      "subcategory": "Xbox One",
      "matricule": "XBO-003",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Xbox Series S",
      "price": 299.99,
      "description": "La console de nouvelle génération de Microsoft, compacte et performante.",
      "quantity": 120,
      "category": "console",
      "subcategory": "Xbox Series",
      "matricule": "XBS-001",
      "memory": "512GB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Xbox Series X",
      "price": 499.99,
      "description": "La console de nouvelle génération de Microsoft avec des performances en 4K.",
      "quantity": 100,
      "category": "console",
      "subcategory": "Xbox Series",
      "matricule": "XBS-002",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Xbox Series S 1TB",
      "price": 349.99,
      "description": "La console de nouvelle génération de Microsoft avec plus de capacité de stockage.",
      "quantity": 110,
      "category": "console",
      "subcategory": "Xbox Series",
      "matricule": "XBS-003",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Xbox Series X 2TB",
      "price": 599.99,
      "description": "La console de nouvelle génération de Microsoft avec une grande capacité de stockage.",
      "quantity": 80,
      "category": "console",
      "subcategory": "Xbox Series",
      "matricule": "XBS-004",
      "memory": "2TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Xbox Series X Limited Edition",
      "price": 699.99,
      "description": "La console de nouvelle génération de Microsoft avec un design unique et des performances en 4K.",
      "quantity": 50,
      "category": "console",
      "subcategory": "Xbox Series",
      "matricule": "XBS-005",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "PlayStation 4",
      "price": 299.99,
      "description": "La console de jeux de Sony avec une large bibliothèque de jeux.",
      "quantity": 150,
      "category": "console",
      "subcategory": "PS4",
      "matricule": "PS4-001",
      "memory": "500GB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "PlayStation 4 Slim",
      "price": 349.99,
      "description": "La version plus mince et plus légère de la PS4.",
      "quantity": 130,
      "category": "console",
      "subcategory": "PS4",
      "matricule": "PS4-002",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "PlayStation 4 Pro",
      "price": 399.99,
      "description": "La version améliorée de la PS4 avec des performances en 4K.",
      "quantity": 120,
      "category": "console",
      "subcategory": "PS4",
      "matricule": "PS4-003",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "PlayStation 4 Pro 2TB",
      "price": 449.99,
      "description": "La version améliorée de la PS4 avec des performances en 4K et plus de capacité de stockage.",
      "quantity": 100,
      "category": "console",
      "subcategory": "PS4",
      "matricule": "PS4-004",
      "memory": "2TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "PlayStation 4 1TB",
      "price": 349.99,
      "description": "La console de jeux de Sony avec plus de capacité de stockage.",
      "quantity": 110,
      "category": "console",
      "subcategory": "PS4",
      "matricule": "PS4-005",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "PlayStation 4 Limited Edition",
      "price": 399.99,
      "description": "La console de jeux de Sony avec un design unique et une large bibliothèque de jeux.",
      "quantity": 70,
      "category": "console",
      "subcategory": "PS4",
      "matricule": "PS4-006",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Xbox Series X Halo Edition",
      "price": 549.99,
      "description": "La console de nouvelle génération de Microsoft avec un design Halo unique.",
      "quantity": 60,
      "category": "console",
      "subcategory": "Xbox Series",
      "matricule": "XBS-006",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Xbox One X Cyberpunk Edition",
      "price": 599.99,
      "description": "La console Xbox One X avec un design unique inspiré de Cyberpunk 2077.",
      "quantity": 40,
      "category": "console",
      "subcategory": "Xbox One",
      "matricule": "XBO-004",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "PlayStation 4 Spider-Man Edition",
      "price": 449.99,
      "description": "La console PS4 avec un design unique inspiré de Spider-Man.",
      "quantity": 50,
      "category": "console",
      "subcategory": "PS4",
      "matricule": "PS4-007",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "PlayStation 4 Pro God of War Edition",
      "price": 499.99,
      "description": "La console PS4 Pro avec un design unique inspiré de God of War.",
      "quantity": 30,
      "category": "console",
      "subcategory": "PS4",
      "matricule": "PS4-008",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "PlayStation 4 Pro Red Dead Redemption Edition",
      "price": 549.99,
      "description": "La console PS4 Pro avec un design unique inspiré de Red Dead Redemption.",
      "quantity": 25,
      "category": "console",
      "subcategory": "PS4",
      "matricule": "PS4-009",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "PlayStation 4 Pro The Last of Us Part II Edition",
      "price": 599.99,
      "description": "La console PS4 Pro avec un design unique inspiré de The Last of Us Part II.",
      "quantity": 20,
      "category": "console",
      "subcategory": "PS4",
      "matricule": "PS4-010",
      "memory": "1TB",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
  {
    "name": "Spider-Man: Miles Morales",
    "price": 49.99,
    "description": "Incarnez Miles Morales alors qu'il découvre ses nouveaux pouvoirs pour devenir son propre Spider-Man.",
    "quantity": 200,
    "category": "jeu",
    "subcategory": "PS5",
    "matricule": "PS5-GAME-001",
    "genre": "Action",
    "platform": "PS5",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Demon's Souls",
    "price": 69.99,
    "description": "Un remake complet du classique de la PlayStation avec des graphismes et un gameplay améliorés.",
    "quantity": 150,
    "category": "jeu",
    "subcategory": "PS5",
    "matricule": "PS5-GAME-002",
    "genre": "RPG",
    "platform": "PS5",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Ratchet & Clank: Rift Apart",
    "price": 69.99,
    "description": "Une aventure interdimensionnelle avec Ratchet et Clank.",
    "quantity": 180,
    "category": "jeu",
    "subcategory": "PS5",
    "matricule": "PS5-GAME-003",
    "genre": "Action",
    "platform": "PS5",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "The Last of Us Part II",
    "price": 59.99,
    "description": "La suite très attendue du jeu acclamé par la critique, The Last of Us.",
    "quantity": 120,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-001",
    "genre": "Action",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Ghost of Tsushima",
    "price": 59.99,
    "description": "Incarnez un samouraï dans une aventure épique à travers le Japon féodal.",
    "quantity": 130,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-002",
    "genre": "Action",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "God of War",
    "price": 39.99,
    "description": "Une nouvelle aventure de Kratos avec son fils Atreus dans le monde des dieux nordiques.",
    "quantity": 140,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-003",
    "genre": "Action",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Horizon Zero Dawn",
    "price": 29.99,
    "description": "Incarnez Aloy et explorez un monde post-apocalyptique peuplé de créatures mécaniques.",
    "quantity": 110,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-004",
    "genre": "RPG",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Cyberpunk 2077",
    "price": 59.99,
    "description": "Un RPG en monde ouvert dans un futur dystopique où les améliorations cybernétiques sont la norme.",
    "quantity": 90,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-005",
    "genre": "RPG",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Red Dead Redemption 2",
    "price": 59.99,
    "description": "Un jeu d'action-aventure épique dans l'Amérique sauvage à la fin du XIXe siècle.",
    "quantity": 100,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-006",
    "genre": "Action",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Uncharted 4: A Thief's End",
    "price": 19.99,
    "description": "Rejoignez Nathan Drake dans sa dernière aventure à travers le monde à la recherche d'un trésor perdu.",
    "quantity": 160,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-007",
    "genre": "Action",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Halo Infinite",
    "price": 59.99,
    "description": "La dernière entrée dans la série Halo, offrant une expérience épique sur Xbox.",
    "quantity": 180,
    "category": "jeu",
    "subcategory": "Xbox Series",
    "matricule": "XBS-GAME-001",
    "genre": "FPS",
    "platform": "Xbox Series",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Forza Horizon 5",
    "price": 59.99,
    "description": "Une expérience de course en monde ouvert à travers les paysages magnifiques du Mexique.",
    "quantity": 200,
    "category": "jeu",
    "subcategory": "Xbox Series",
    "matricule": "XBS-GAME-002",
    "genre": "Racing",
    "platform": "Xbox Series",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Gears 5",
    "price": 39.99,
    "description": "Un jeu de tir à la troisième personne intense dans un monde post-apocalyptique.",
    "quantity": 140,
    "category": "jeu",
    "subcategory": "Xbox Series",
    "matricule": "XBS-GAME-003",
    "genre": "TPS",
    "platform": "Xbox Series",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Assassin's Creed Valhalla",
    "price": 59.99,
    "description": "Incarnez Eivor, un Viking, et partez à la conquête de l'Angleterre.",
    "quantity": 150,
    "category": "jeu",
    "subcategory": "Xbox Series",
    "matricule": "XBS-GAME-004",
    "genre": "Action",
    "platform": "Xbox Series",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "FIFA 22",
    "price": 59.99,
    "description": "La dernière édition du célèbre jeu de football avec des graphismes améliorés et de nouvelles fonctionnalités.",
    "quantity": 190,
    "category": "jeu",
    "subcategory": "Xbox Series",
    "matricule": "XBS-GAME-005",
    "genre": "Sports",
    "platform": "Xbox Series",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Madden NFL 22",
    "price": 59.99,
    "description": "La dernière édition du célèbre jeu de football américain avec des graphismes améliorés et de nouvelles fonctionnalités.",
    "quantity": 180,
    "category": "jeu",
    "subcategory": "Xbox Series",
    "matricule": "XBS-GAME-006",
    "genre": "Sports",
    "platform": "Xbox Series",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "NBA 2K22",
    "price": 59.99,
    "description": "La dernière édition du célèbre jeu de basketball avec des graphismes améliorés et de nouvelles fonctionnalités.",
    "quantity": 170,
    "category": "jeu",
    "subcategory": "Xbox Series",
    "matricule": "XBS-GAME-007",
    "genre": "Sports",
    "platform": "Xbox Series",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Call of Duty: Black Ops Cold War",
    "price": 59.99,
    "description": "Un jeu de tir à la première personne intense se déroulant pendant la guerre froide.",
    "quantity": 160,
    "category": "jeu",
    "subcategory": "Xbox Series",
    "matricule": "XBS-GAME-008",
    "genre": "FPS",
    "platform": "Xbox Series",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Resident Evil Village",
    "price": 59.99,
    "description": "Un jeu d'horreur et de survie où vous explorez un mystérieux village.",
    "quantity": 140,
    "category": "jeu",
    "subcategory": "Xbox Series",
    "matricule": "XBS-GAME-009",
    "genre": "Horror",
    "platform": "Xbox Series",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Cyberpunk 2077",
    "price": 59.99,
    "description": "Un RPG en monde ouvert dans un futur dystopique où les améliorations cybernétiques sont la norme.",
    "quantity": 130,
    "category": "jeu",
    "subcategory": "Xbox One",
    "matricule": "XBO-GAME-001",
    "genre": "RPG",
    "platform": "Xbox One",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Red Dead Redemption 2",
    "price": 59.99,
    "description": "Un jeu d'action-aventure épique dans l'Amérique sauvage à la fin du XIXe siècle.",
    "quantity": 120,
    "category": "jeu",
    "subcategory": "Xbox One",
    "matricule": "XBO-GAME-002",
    "genre": "Action",
    "platform": "Xbox One",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "The Witcher 3: Wild Hunt",
    "price": 39.99,
    "description": "Un RPG en monde ouvert où vous incarnez Geralt de Riv, un chasseur de monstres.",
    "quantity": 110,
    "category": "jeu",
    "subcategory": "Xbox One",
    "matricule": "XBO-GAME-003",
    "genre": "RPG",
    "platform": "Xbox One",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "GTA V",
    "price": 29.99,
    "description": "Un jeu d'action-aventure en monde ouvert se déroulant dans la ville fictive de Los Santos.",
    "quantity": 190,
    "category": "jeu",
    "subcategory": "Xbox One",
    "matricule": "XBO-GAME-004",
    "genre": "Action",
    "platform": "Xbox One",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Assassin's Creed Odyssey",
    "price": 49.99,
    "description": "Un RPG d'action se déroulant dans la Grèce antique.",
    "quantity": 160,
    "category": "jeu",
    "subcategory": "Xbox One",
    "matricule": "XBO-GAME-005",
    "genre": "Action",
    "platform": "Xbox One",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Halo: The Master Chief Collection",
    "price": 39.99,
    "description": "Une compilation des jeux Halo avec des graphismes améliorés et un multijoueur en ligne.",
    "quantity": 150,
    "category": "jeu",
    "subcategory": "Xbox One",
    "matricule": "XBO-GAME-006",
    "genre": "FPS",
    "platform": "Xbox One",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Forza Horizon 4",
    "price": 49.99,
    "description": "Une expérience de course en monde ouvert à travers les paysages magnifiques de Grande-Bretagne.",
    "quantity": 170,
    "category": "jeu",
    "subcategory": "Xbox One",
    "matricule": "XBO-GAME-007",
    "genre": "Racing",
    "platform": "Xbox One",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "FIFA 21",
    "price": 59.99,
    "description": "La dernière édition du célèbre jeu de football avec des graphismes améliorés et de nouvelles fonctionnalités.",
    "quantity": 190,
    "category": "jeu",
    "subcategory": "Xbox One",
    "matricule": "XBO-GAME-008",
    "genre": "Sports",
    "platform": "Xbox One",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Madden NFL 21",
    "price": 59.99,
    "description": "La dernière édition du célèbre jeu de football américain avec des graphismes améliorés et de nouvelles fonctionnalités.",
    "quantity": 180,
    "category": "jeu",
    "subcategory": "Xbox One",
    "matricule": "XBO-GAME-009",
    "genre": "Sports",
    "platform": "Xbox One",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "NBA 2K21",
    "price": 59.99,
    "description": "La dernière édition du célèbre jeu de basketball avec des graphismes améliorés et de nouvelles fonctionnalités.",
    "quantity": 170,
    "category": "jeu",
    "subcategory": "Xbox One",
    "matricule": "XBO-GAME-010",
    "genre": "Sports",
    "platform": "Xbox One",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Spider-Man",
    "price": 39.99,
    "description": "Incarnez Spider-Man et protégez New York dans cette aventure épique.",
    "quantity": 160,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-008",
    "genre": "Action",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Bloodborne",
    "price": 29.99,
    "description": "Un jeu d'action-RPG intense dans un monde gothique plein de monstres et de mystères.",
    "quantity": 110,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-009",
    "genre": "RPG",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Gran Turismo Sport",
    "price": 39.99,
    "description": "Un jeu de course réaliste avec une large sélection de voitures et de circuits.",
    "quantity": 100,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-010",
    "genre": "Racing",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Nioh 2",
    "price": 59.99,
    "description": "Un jeu d'action-RPG se déroulant dans un Japon fantastique rempli de créatures surnaturelles.",
    "quantity": 90,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-011",
    "genre": "RPG",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Sekiro: Shadows Die Twice",
    "price": 59.99,
    "description": "Un jeu d'action-aventure se déroulant dans un Japon féodal où vous incarnez un shinobi.",
    "quantity": 80,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-012",
    "genre": "Action",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Marvel's Avengers",
    "price": 59.99,
    "description": "Un jeu d'action-aventure où vous incarnez vos super-héros préférés de Marvel.",
    "quantity": 70,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-013",
    "genre": "Action",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Days Gone",
    "price": 39.99,
    "description": "Un jeu d'action-aventure en monde ouvert où vous incarnez un motard dans un monde post-apocalyptique.",
    "quantity": 60,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-014",
    "genre": "Action",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Final Fantasy VII Remake",
    "price": 59.99,
    "description": "Une réimagination moderne du classique RPG Final Fantasy VII.",
    "quantity": 50,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-015",
    "genre": "RPG",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Death Stranding",
    "price": 59.99,
    "description": "Un jeu d'action-aventure unique créé par Hideo Kojima.",
    "quantity": 40,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-016",
    "genre": "Action",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Control",
    "price": 39.99,
    "description": "Un jeu d'action-aventure où vous incarnez Jesse Faden qui découvre des pouvoirs surnaturels.",
    "quantity": 70,
    "category": "jeu",
    "subcategory": "PS4",
    "matricule": "PS4-GAME-017",
    "genre": "Action",
    "platform": "PS4",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Elden Ring",
    "price": 59.99,
    "description": "Un RPG d'action en monde ouvert créé par FromSoftware et George R.R. Martin.",
    "quantity": 120,
    "category": "jeu",
    "subcategory": "PS5",
    "matricule": "PS5-GAME-004",
    "genre": "RPG",
    "platform": "PS5",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Horizon Forbidden West",
    "price": 69.99,
    "description": "La suite du jeu acclamé Horizon Zero Dawn avec Aloy explorant l'ouest américain.",
    "quantity": 130,
    "category": "jeu",
    "subcategory": "PS5",
    "matricule": "PS5-GAME-005",
    "genre": "RPG",
    "platform": "PS5",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Resident Evil Village",
    "price": 59.99,
    "description": "Un jeu d'horreur et de survie où vous explorez un mystérieux village.",
    "quantity": 140,
    "category": "jeu",
    "subcategory": "PS5",
    "matricule": "PS5-GAME-006",
    "genre": "Horror",
    "platform": "PS5",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Returnal",
    "price": 69.99,
    "description": "Un jeu de tir roguelike où vous incarnez une astronaute coincée dans une boucle temporelle.",
    "quantity": 150,
    "category": "jeu",
    "subcategory": "PS5",
    "matricule": "PS5-GAME-007",
    "genre": "Action",
    "platform": "PS5",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Kena: Bridge of Spirits",
    "price": 49.99,
    "description": "Un jeu d'action-aventure charmant avec une jeune guide spirituelle.",
    "quantity": 160,
    "category": "jeu",
    "subcategory": "PS5",
    "matricule": "PS5-GAME-008",
    "genre": "Action",
    "platform": "PS5",
    "front_pic": null,
    "back_pic": null
  },
  {
    "name": "Ratchet & Clank: Rift Apart",
    "price": 69.99,
    "description": "Une aventure interdimensionnelle avec Ratchet et Clank.",
    "quantity": 170,
    "category": "jeu",
    "subcategory": "PS5",
    "matricule": "PS5-GAME-009",
    "genre": "Action",
    "platform": "PS5",
    "front_pic": null,
    "back_pic": null
  }
  ,
    {
      "name": "Manette DualSense PS5",
      "price": 69.99,
      "description": "La manette sans fil officielle pour PlayStation 5 avec retour haptique et gâchettes adaptatives.",
      "quantity": 100,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A001",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Station de chargement DualSense PS5",
      "price": 29.99,
      "description": "Station de chargement pour deux manettes DualSense pour PlayStation 5.",
      "quantity": 80,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A002",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Casque Pulse 3D PS5",
      "price": 99.99,
      "description": "Casque audio sans fil officiel pour PlayStation 5 avec audio 3D.",
      "quantity": 60,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A003",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Manette DualShock 4 PS4",
      "price": 59.99,
      "description": "La manette sans fil officielle pour PlayStation 4 avec retour tactile.",
      "quantity": 100,
      "category": "accessoire",
      "subcategory": "PS4",
      "matricule": "PS4-A001",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Station de chargement DualShock 4 PS4",
      "price": 24.99,
      "description": "Station de chargement pour deux manettes DualShock 4 pour PlayStation 4.",
      "quantity": 90,
      "category": "accessoire",
      "subcategory": "PS4",
      "matricule": "PS4-A002",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Casque Sony PS4 Gold Wireless",
      "price": 89.99,
      "description": "Casque audio sans fil pour PlayStation 4 avec son surround virtuel.",
      "quantity": 70,
      "category": "accessoire",
      "subcategory": "PS4",
      "matricule": "PS4-A003",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Manette Xbox Wireless",
      "price": 64.99,
      "description": "La manette sans fil officielle pour Xbox One avec des améliorations de prise en main.",
      "quantity": 110,
      "category": "accessoire",
      "subcategory": "Xbox One",
      "matricule": "XBO-A001",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Station de chargement Xbox One",
      "price": 29.99,
      "description": "Station de chargement pour deux manettes Xbox One.",
      "quantity": 75,
      "category": "accessoire",
      "subcategory": "Xbox One",
      "matricule": "XBO-A002",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Casque Xbox Wireless",
      "price": 99.99,
      "description": "Casque audio sans fil officiel pour Xbox avec audio surround.",
      "quantity": 50,
      "category": "accessoire",
      "subcategory": "Xbox One",
      "matricule": "XBO-A003",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Manette Xbox Series X/S",
      "price": 69.99,
      "description": "La manette sans fil officielle pour Xbox Series X/S avec des améliorations de prise en main.",
      "quantity": 100,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A001",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Station de chargement Xbox Series X/S",
      "price": 34.99,
      "description": "Station de chargement pour deux manettes Xbox Series X/S.",
      "quantity": 85,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A002",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Casque Xbox Series X Wireless",
      "price": 119.99,
      "description": "Casque audio sans fil pour Xbox Series X/S avec son surround et support Dolby Atmos.",
      "quantity": 60,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A003",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Manette PS5 DualSense Charging Dock",
      "price": 29.99,
      "description": "Station de chargement officielle pour deux manettes DualSense pour PS5.",
      "quantity": 85,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A004",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Housse de protection PS5",
      "price": 19.99,
      "description": "Housse de protection en silicone pour la PlayStation 5.",
      "quantity": 70,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A005",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Ventilateur de refroidissement PS5",
      "price": 24.99,
      "description": "Ventilateur de refroidissement externe pour la PlayStation 5.",
      "quantity": 60,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A006",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Manette PS4 DualShock 4 Charging Dock",
      "price": 24.99,
      "description": "Station de chargement pour deux manettes DualShock 4 pour PS4.",
      "quantity": 80,
      "category": "accessoire",
      "subcategory": "PS4",
      "matricule": "PS4-A004",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Housse de protection PS4",
      "price": 19.99,
      "description": "Housse de protection en silicone pour la PlayStation 4.",
      "quantity": 75,
      "category": "accessoire",
      "subcategory": "PS4",
      "matricule": "PS4-A004",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Manette Xbox One Charging Dock",
      "price": 29.99,
      "description": "Station de chargement pour deux manettes Xbox One.",
      "quantity": 80,
      "category": "accessoire",
      "subcategory": "Xbox One",
      "matricule": "XBO-A004",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Housse de protection Xbox One",
      "price": 19.99,
      "description": "Housse de protection en silicone pour la Xbox One.",
      "quantity": 65,
      "category": "accessoire",
      "subcategory": "Xbox One",
      "matricule": "XBO-A005",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Manette Xbox Series X/S Elite",
      "price": 179.99,
      "description": "Manette Elite sans fil pour Xbox Series X/S avec des options de personnalisation avancées.",
      "quantity": 50,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A004",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Support de console PS5",
      "price": 19.99,
      "description": "Support de console pour la PlayStation 5, permet de la placer en position verticale ou horizontale.",
      "quantity": 70,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A007",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Support de console PS4",
      "price": 17.99,
      "description": "Support de console pour la PlayStation 4, permet de la placer en position verticale ou horizontale.",
      "quantity": 65,
      "category": "accessoire",
      "subcategory": "PS4",
      "matricule": "PS4-A005",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Ventilateur de refroidissement Xbox Series X",
      "price": 24.99,
      "description": "Ventilateur de refroidissement externe pour la Xbox Series X.",
      "quantity": 55,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A005",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Support de console Xbox Series X",
      "price": 19.99,
      "description": "Support de console pour la Xbox Series X, permet de la placer en position verticale ou horizontale.",
      "quantity": 60,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A006",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Manette Xbox Series X/S Wireless Charging Dock",
      "price": 34.99,
      "description": "Station de chargement pour deux manettes Xbox Series X/S.",
      "quantity": 65,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A007",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Casque de jeu PS5 7.1 Surround",
      "price": 129.99,
      "description": "Casque de jeu avec son surround 7.1 pour une immersion totale sur PS5.",
      "quantity": 50,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A008",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Manette PS5 DualSense Midnight Black",
      "price": 74.99,
      "description": "Manette DualSense PS5 en édition spéciale Midnight Black.",
      "quantity": 45,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A009",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Manette Xbox One Wireless Midnight Blue",
      "price": 69.99,
      "description": "Manette sans fil Xbox One en édition spéciale Midnight Blue.",
      "quantity": 55,
      "category": "accessoire",
      "subcategory": "Xbox One",
      "matricule": "XBO-A006",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Casque Xbox One Stereo",
      "price": 69.99,
      "description": "Casque audio stéréo officiel pour Xbox One avec micro intégré.",
      "quantity": 40,
      "category": "accessoire",
      "subcategory": "Xbox One",
      "matricule": "XBO-A007",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Câble de chargement PS5",
      "price": 14.99,
      "description": "Câble USB-C pour la recharge des manettes DualSense de PS5.",
      "quantity": 100,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A010",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Câble de chargement Xbox Series X",
      "price": 14.99,
      "description": "Câble USB-C pour la recharge des manettes Xbox Series X/S.",
      "quantity": 90,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A008",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Pochette de rangement PS5",
      "price": 24.99,
      "description": "Pochette de rangement pour les jeux et accessoires de la PlayStation 5.",
      "quantity": 65,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A011",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Pochette de rangement Xbox Series X",
      "price": 24.99,
      "description": "Pochette de rangement pour les jeux et accessoires de la Xbox Series X/S.",
      "quantity": 60,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A009",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Support pour manettes PS5",
      "price": 15.99,
      "description": "Support pour ranger les manettes DualSense de PS5.",
      "quantity": 70,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A012",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Support pour manettes Xbox Series X",
      "price": 15.99,
      "description": "Support pour ranger les manettes Xbox Series X/S.",
      "quantity": 60,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A010",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Chargeur rapide PS4",
      "price": 34.99,
      "description": "Chargeur rapide pour manettes DualShock 4 de PS4.",
      "quantity": 55,
      "category": "accessoire",
      "subcategory": "PS4",
      "matricule": "PS4-A006",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Chargeur rapide Xbox One",
      "price": 34.99,
      "description": "Chargeur rapide pour manettes Xbox One.",
      "quantity": 50,
      "category": "accessoire",
      "subcategory": "Xbox One",
      "matricule": "XBO-A008",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Gant de nettoyage pour console",
      "price": 12.99,
      "description": "Gant de nettoyage en microfibre pour les consoles PS5, PS4, Xbox One et Xbox Series X/S.",
      "quantity": 100,
      "category": "accessoire",
      "subcategory": "entretien",
      "matricule": "ENT-A001",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Adaptateur Bluetooth PS5",
      "price": 19.99,
      "description": "Adaptateur Bluetooth pour connecter des accessoires sans fil à la PlayStation 5.",
      "quantity": 45,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A013",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Adaptateur Bluetooth Xbox Series X",
      "price": 19.99,
      "description": "Adaptateur Bluetooth pour connecter des accessoires sans fil à la Xbox Series X/S.",
      "quantity": 50,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A011",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Manette PS4 DualShock 4 Red Camouflage",
      "price": 64.99,
      "description": "Manette DualShock 4 pour PS4 en édition spéciale Red Camouflage.",
      "quantity": 40,
      "category": "accessoire",
      "subcategory": "PS4",
      "matricule": "PS4-A007",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Support de casque PS5",
      "price": 14.99,
      "description": "Support pour ranger le casque audio de PS5.",
      "quantity": 65,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A014",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Support de casque Xbox Series X",
      "price": 14.99,
      "description": "Support pour ranger le casque audio de Xbox Series X/S.",
      "quantity": 55,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A012",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Câble HDMI 4K PS5",
      "price": 19.99,
      "description": "Câble HDMI haute vitesse pour une connexion 4K avec la PlayStation 5.",
      "quantity": 80,
      "category": "accessoire",
      "subcategory": "PS5",
      "matricule": "PS5-A015",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Câble HDMI 4K Xbox Series X",
      "price": 19.99,
      "description": "Câble HDMI haute vitesse pour une connexion 4K avec la Xbox Series X/S.",
      "quantity": 70,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A013",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Tapis de souris gaming PS4",
      "price": 17.99,
      "description": "Tapis de souris de grande taille avec logo PlayStation pour PS4.",
      "quantity": 60,
      "category": "accessoire",
      "subcategory": "PS4",
      "matricule": "PS4-A008",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    },
    {
      "name": "Tapis de souris gaming Xbox Series X",
      "price": 17.99,
      "description": "Tapis de souris de grande taille avec logo Xbox pour Xbox Series X/S.",
      "quantity": 55,
      "category": "accessoire",
      "subcategory": "Xbox Series",
      "matricule": "XBS-A014",
      "front_pic": null,
      "back_pic": null,
      "left_pic": null,
      "right_pic": null,
      "up_pic": null,
      "down_pic": null
    }
]  
module.exports = items